---
  - name: "EKS-A config Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: "execute a ls -lrt command"
      shell: "echo <+matrix.site_no>"
      shell: "ls -lrt"
      register: "output"

    - debug: var=output.stdout_lines
