---
  - name: "EKS-A config Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: "execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output1"
      
    - debug: var=output1.stdout_lines
      
    - name: Basic usage
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'site_no') }}' is the site number."
