---
  - name: "EKS-A config Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: "execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output1"
      
    - debug: var=output1.stdout_lines
      
    - name: "site info"
      shell: "echo '<+matrix.site_no>'"
      register: "output"

    - debug: var=output.stdout_lines
